# propiesties para el perfil: default

# Propiedades de conexion un contenedor con un puerto mapeado a: localhost -> 5672:5672
spring.application.name=sensorIngestData
server.port=8010

spring.kafka.bootstrap-servers=localhost:9092


telemetry.topic.sensor-data=sensor-telemetry-data