server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
    renewal-percent-threshold: 0.85
    renewal-threshold-update-interval-ms: 900000
